name: 'My Job will help to Planning for display Message'
on: [push]
jobs:
  Job-Message-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to Github Runner Operating System is ${{runner.os}}"
      - run: echo "Github Event Name is ${{github.event_name}}"
      - run: ls ~
      - run: pwd
      - run: ls ${{ github.workspace }}
